### PR TITLE
Fix macro hygiene

### PR DESCRIPTION
**Pull request by charleskawczynski**
Found in https://buildkite.com/clima/climacoupler-ci/builds/1372#01895016-b183-41a3-93fc-fbef7e2cf455/142-211, this PR:

 - Improves the macro hygiene test
 - Fixes some macro hygiene issues

### CODE REVIEW

**Review by simonbyrne — APPROVED** [review]

**Comment by charleskawczynski** [comment]
It ran locally because I forgot to re-dev my test env. Still figuring out how to fix this..

**Comment by charleskawczynski** [comment]
Ugh, we're running into https://github.com/JuliaLang/julia/issues/37691

**Comment by simonbyrne** [comment]
what's the issue?

**Comment by simonbyrne** [comment]
Oh, `@threads`....

**Comment by charleskawczynski** [comment]
Yeah, from https://discourse.julialang.org/t/optional-macro-invocation/18588/21?page=2:

```julia
macro threaded(device, loop::Expr)
  quote if $(esc(device)) isa CPUMultiThreaded
         Threads.@threads $(Expr(loop.head,
                            Expr(loop.args[1].head, esc.(loop.args[1].args)...),
                            esc(loop.args[2])))
      else
        @assert $(esc(device)) isa AbstractDevice
        # @warn "running single threaded"
        $(esc(loop))
      end
  end
end
```
seems to work

**Comment by simonbyrne** [comment]
that might be the least-worst solution

**Pull request merged**
