### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by glwagner**
This PR fixes a small typo on the home page of the ClimaComms documentation.

### CODE REVIEW

**Comment by glwagner** [comment]
I'm actually assuming that the fix is correct but I am not 100% sure

**Comment by glwagner** [comment]
I also fixed the syntax for a warning

**Comment by glwagner** [comment]
Might be good to add protections on the `main` branch for the package?

**Review by Sbozzolo — APPROVED** [review]

**Comment by Sbozzolo** [comment]
> Might be good to add protections on the `main` branch for the package?

There should be?

**Comment by glwagner** [comment]
Hmm ok it looked like I could merge with no approvals but perhaps I was wrong !

**Comment by Sbozzolo** [comment]
Ah, yes, you can merge with no reviews, but you cannot push to main and tests have to pass.

**Pull request merged**
