### PR TITLE
Move buildkite to new central

### LINKED ISSUE #72: Move to new-central/MPITrampoline
Move ClimaComms to new-central. This is not straightforward because of https://github.com/JuliaParallel/MPI.jl/issues/820.

### PR DESCRIPTION
**Pull request by Sbozzolo**
And use climacommon :)

Closes #72

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Ok, one conceptual issue is that the threaded tests are being launched with `--threads 8`, and `runsingleton` does not take this into account. I think reverting the `runsingleton` change should fix this.

**Comment by Sbozzolo** [comment]
> Ok, one conceptual issue is that the threaded tests are being launched with `--threads 8`, and `runsingleton` does not take this into account. I think reverting the `runsingleton` change should fix this.

I don't thinks that's the case. If we are not running with MPI (as in the threaded test), the context should be singleton. It is the device that would change to `CPUMultiThreaded`.

**Comment by charleskawczynski** [comment]
I don't think it's the problem we're seeing, but it is a conceptual issue: we end up reducing coverage if we don't run `basic.jl` in multithreaded mode.

**Comment by Sbozzolo** [comment]
> I don't think it's the problem we're seeing, but it is a conceptual issue: we end up reducing coverage if we don't run `basic.jl` in multithreaded mode.

Singleton and mutli-threaded are not mutually exclusive. 

This is how singleton is picked by `ClimaComms.context`:
```julia
function context(device = device())
    name = get(ENV, "CLIMACOMMS_CONTEXT", nothing)
    if !isnothing(name)
        if name == "MPI"
            return MPICommsContext()
        elseif name == "SINGLETON"
            return SingletonCommsContext()
        else
            error("Invalid context: $name")
        end
    end
    # detect common environment variables used by MPI launchers
    #   PMI_RANK appears to be used by MPICH and srun
    #   OMPI_COMM_WORLD_RANK appears to be used by OpenMPI
    if haskey(ENV, "PMI_RANK") || haskey(ENV, "OMPI_COMM_WORLD_RANK")
        return MPICommsContext(device)
    else
        return SingletonCommsContext(device)
    end
end
```

What I understand from this is that the context should be singleton when you are not running with MPI.

**Comment by charleskawczynski** [comment]
> Singleton and mutli-threaded are not mutually exclusive.

I understand that, but `Base.julia_cmd()` in the launch

```julia
function runsingleton(file)
    Base.run(
        Cmd(
            `$(Base.julia_cmd()) --startup-file=no --project=$(Base.active_project()) $file`,
            env = ("CLIMACOMMS_CONTEXT" => "SINGLETON",),
        ),
    )
end
```
does not propagate multiple threads:

```
Base.julia_cmd(juliapath=joinpath(Sys.BINDIR, julia_exename()); cpu_target::Union{Nothing,String}=nothing)

  Return a julia command similar to the one of the running process. Propagates any of the --cpu-target, --sysimage,
  --compile, --sysimage-native-code, --compiled-modules, --pkgimages, --inline, --check-bounds, --optimize,
  --min-optlevel, -g, --code-coverage, --track-allocation, --color, --startup-file, and --depwarn command line arguments
  that are not at their default values.
```

**Pull request closed without merging**
